spring.application.name=VisitorManagementSystem
server.port=${PORT:8080}

# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB:vms}

# Mail Configuration
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=${EMAIL_FROM:${SMTP_USER}}

# OTP Configuration
otp.expiry.minutes=${OTP_EXPIRY_MINUTES:5}

# Security (Production - Ensure these are set in env!)
jwt.secret=${JWT_SECRET}

# Cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Multipart configuration
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
